# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenRecurringAPI.Model.DisableRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"contract",
    :"merchantAccount",
    :"recurringDetailReference",
    :"shopperReference"
  ]

  @type t :: %__MODULE__{
    :"contract" => String.t | nil,
    :"merchantAccount" => String.t,
    :"recurringDetailReference" => String.t | nil,
    :"shopperReference" => String.t
  }
end

defimpl Poison.Decoder, for: AdyenRecurringAPI.Model.DisableRequest do
  def decode(value, _options) do
    value
  end
end

