# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenRecurringAPI.Model.Name1 do
  @moduledoc """
  The name of the shopper.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"firstName",
    :"lastName"
  ]

  @type t :: %__MODULE__{
    :"firstName" => String.t,
    :"lastName" => String.t
  }
end

defimpl Poison.Decoder, for: AdyenRecurringAPI.Model.Name1 do
  def decode(value, _options) do
    value
  end
end

