# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenRecurringAPI.Model.Recurring1 do
  @moduledoc """
  A container for the type of a recurring contract to be retrieved.  The contract value needs to match the contract value submitted in the payment transaction used to create a recurring contract. However, if `ONECLICK,RECURRING` is the original contract definition in the initial payment, then `contract` should take either `ONECLICK` or `RECURRING`, depending on whether or not you want the shopper to enter their card's security code when they finalize their purchase.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"contract",
    :"recurringDetailName",
    :"recurringExpiry",
    :"recurringFrequency",
    :"tokenService"
  ]

  @type t :: %__MODULE__{
    :"contract" => AdyenRecurringAPI.Model.Contract.t | nil,
    :"recurringDetailName" => String.t | nil,
    :"recurringExpiry" => String.t | nil,
    :"recurringFrequency" => String.t | nil,
    :"tokenService" => AdyenRecurringAPI.Model.TokenService.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenRecurringAPI.Model.Recurring1 do
  import AdyenRecurringAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"contract", :struct, AdyenRecurringAPI.Model.Contract, options)
    |> deserialize(:"tokenService", :struct, AdyenRecurringAPI.Model.TokenService, options)
  end
end

